conf:
  connections:
    - name: demodb    
      baseFolder: file:conf/postgresql/database
      url: jdbc:postgresql://db:54321/demo
      user: postgres
      password: postgres

server:
     port: 8007
