version: '3'
services:

  db:
    image: mgramin/postgres-pro-demodb-small
    ports:
      - 5432
    networks:
      mynetwork:
        aliases:
          - db_server
    hostname: db_server

  sql-boot:
    build: . 
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db
    links:
      - db
    environment:
      profile: postgres
      db_dev_user: postgres
      db_dev_password: postgres
      db_dev_url: jdbc:postgresql://db:5432/demo


networks:
  mynetwork:
    driver: bridge
