version: '3'
services:
  db:
    image: mgramin/postgres-pro-demodb-small
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        aliases:
          - db_server
    hostname: db_server

  sql-boot:
    build: . 
    ports:
      - "8007:8007"
    networks:
      - mynetwork
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/sql-boot/conf/postgresql
      - ./application.yml:/sql-boot/application.yml


networks:
  mynetwork:
    driver: bridge
